// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yowiktapcddafwvgprll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvd2lrdGFwY2RkYWZ3dmdwcmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxOTIxNDQsImV4cCI6MjA1Mzc2ODE0NH0.vY0jXMeeLyRD1VViLW0AcQCIzR5p6euBPkUDoVSEBLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);